# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ml_nbdev',
                'doc_host': 'https://gdario.github.io',
                'git_url': 'https://github.com/gdario/ml_nbdev',
                'lib_path': 'ml_nbdev'},
  'syms': {'ml_nbdev.core': {'ml_nbdev.core.plot_random_face': ('get_data.html#plot_random_face', 'ml_nbdev/core.py')}}}
