# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_get_data.ipynb.

# %% auto 0
__all__ = ['plot_random_face']

# %% ../nbs/00_get_data.ipynb 8
def plot_random_face(faces_dset):
    """Plot a randomly selected face from the Olivetti faces dataset
    
    faces_dset: the scikit-learn dataset containing the faces.
    """
    img = faces_dset[np.random.randint(low=0, high=400, size=1)]
    plt.imshow(img.reshape(64, 64))
    plt.show()
